# Generated by Django 5.2.3 on 2025-06-18 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField()),
                ('gst', models.CharField(choices=[('0', 'NIL'), ('5', 'GST 5%'), ('12', 'GST 12%'), ('18', 'GST 18%'), ('28', 'GST 28%')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gst', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(max_length=15, unique=True)),
                ('inv_date', models.DateField()),
                ('remark', models.TextField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('gst', models.CharField(max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoiceapp.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='invoices', through='invoiceapp.InvoiceItem', to='invoiceapp.item'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.party'),
        ),
    ]
