# Generated by Django 5.2.3 on 2025-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_item_party_invoice_invoiceitem_invoice_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
